### ISSUE TITLE
[feat] ScheduleLine 구현하기

### ISSUE THREAD

**Issue by Jin-s-work** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#75]
# Description ✨
LineArea에서 드래그를 하면 ScheduleLine이 나오는 기능 구현하기

# TODO
- [x] 드래그 한 위치 파악해서 ScheduleLine이 그려지게 만들기
- [x] ScheduleAreaView 만들기
- [x] TCA 구조에 맞게 코드 짜기

**Comment by dayo2n** [comment]
close with #93
